#!/usr/bin/env python3
"""
SketchUp adapter for PDF Vector Importer QA.

Purpose:
- Provides a stable command-line interface for the external test runner.
- Prepares a JSON payload for a Ruby-side harness script.
- Optionally launches SketchUp with a test script.
- Supports dry-run mode for environments where SketchUp cannot be launched.

This adapter does NOT require changes to the main extension. It assumes you will
add a small Ruby harness that:
1) reads the payload file,
2) performs the import,
3) writes a result JSON file.

Typical use:
python adapters/sketchup_adapter.py --config qa_config.json --test-id SU-OCG-001 --input "C:/tests/1071 - Rev 0.pdf" --preset Full --dry-run
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple


def load_json(path: Optional[str]) -> dict:
    if not path:
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def normalize_path(value: Optional[str], base_dir: Optional[str] = None) -> Optional[str]:
    if value is None:
        return None
    raw = os.path.expandvars(str(value))
    p = Path(raw).expanduser()
    if not p.is_absolute() and base_dir:
        p = Path(base_dir) / p
    return str(p.resolve())


def build_payload(args: argparse.Namespace, cfg: dict, result_path: str, config_dir: Optional[str]) -> dict:
    sketchup_cfg = cfg.get("sketchup", {})
    return {
        "adapter": "sketchup",
        "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "test_id": args.test_id,
        "platform": "SU",
        "input_pdf": normalize_path(args.input, config_dir),
        "preset": args.preset,
        "page_range": args.page_range,
        "output_dir": normalize_path(args.output_dir, config_dir) if args.output_dir else None,
        "result_json": result_path,
        "extension_root": normalize_path(sketchup_cfg.get("extension_root"), config_dir),
        "plugins_dir": normalize_path(sketchup_cfg.get("plugins_dir"), config_dir),
        "ruby_harness": normalize_path(sketchup_cfg.get("ruby_harness"), config_dir),
        "expected": {
            "layers_min_populated": args.layers_min_populated,
            "runtime_cap_seconds": args.runtime_cap_seconds,
        },
        "notes": args.notes or "",
    }


def write_bootstrap_plugin(plugins_dir: str, harness_path: str) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    bootstrap_path = os.path.join(plugins_dir, f"zz_bc_pdf_qa_bootstrap_{ts}.rb")
    ruby = """# Auto-generated by sketchup_adapter.py
begin
  payload = ENV["BC_PDF_QA_PAYLOAD"].to_s
  harness = ENV["BC_PDF_QA_HARNESS"].to_s
  if !payload.strip.empty? && !harness.strip.empty? && File.file?(harness)
    load harness
  end
rescue Exception => e
  begin
    require "json"
    payload_path = ENV["BC_PDF_QA_PAYLOAD"].to_s
    if !payload_path.strip.empty? && File.file?(payload_path)
      payload_data = JSON.parse(File.read(payload_path)) rescue {}
      result_path = payload_data["result_json"].to_s
      unless result_path.strip.empty?
        File.open(result_path, "w") do |f|
          f.write(JSON.pretty_generate({
            "platform" => "SU",
            "status" => "FAIL",
            "message" => "Bootstrap error: #{e.class}: #{e.message}"
          }))
        end
      end
    end
  rescue Exception
  end
end
"""
    with open(bootstrap_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(ruby)
    return bootstrap_path


def cleanup_bootstrap_plugin(path: Optional[str]) -> None:
    if not path:
        return
    try:
        if os.path.isfile(path):
            os.remove(path)
    except OSError:
        pass


def try_launch_sketchup(sketchup_exe: Optional[str], ruby_harness: Optional[str], payload_path: str,
                        config_dir: Optional[str], plugins_dir: Optional[str]) -> Tuple[bool, str, Optional[str]]:
    """
    Best-effort launcher.

    SketchUp does not provide a great official headless CLI for automated plugin
    testing, so this function is intentionally conservative:
    - If executable and harness are provided, launch SketchUp and pass the harness path.
    - The Ruby harness should know to read the payload JSON and write the result JSON.
    """
    if not sketchup_exe:
        return False, "No SketchUp executable configured.", None
    if not ruby_harness:
        return False, "No Ruby harness configured.", None

    exe = normalize_path(sketchup_exe, config_dir)
    harness = normalize_path(ruby_harness, config_dir)
    plugin_root = normalize_path(plugins_dir, config_dir) if plugins_dir else None
    if not os.path.isfile(exe):
        return False, f"SketchUp executable not found: {exe}", None
    if not os.path.isfile(harness):
        return False, f"Ruby harness not found: {harness}", None
    if not plugin_root or not os.path.isdir(plugin_root):
        return False, f"SketchUp plugins_dir not found: {plugin_root}", None

    env = os.environ.copy()
    env["BC_PDF_QA_PAYLOAD"] = payload_path
    env["BC_PDF_QA_HARNESS"] = harness

    bootstrap_path = None
    try:
        bootstrap_path = write_bootstrap_plugin(plugin_root, harness)
    except (OSError, ValueError, TypeError) as exc:
        return False, f"Failed to create bootstrap plugin: {exc}", None

    # Some SketchUp builds accept a Ruby startup script through a file association
    # or command-line file open flow; many do not. We therefore launch SketchUp and
    # let the Ruby harness/bootstrap in Plugins handle the payload.
    try:
        # SketchUp supports Ruby startup scripts on many builds. If unsupported,
        # SketchUp still launches and plugin-side bootstrap can read BC_PDF_QA_PAYLOAD.
        subprocess.Popen([exe, "-RubyStartup", harness], env=env)
        return True, "SketchUp launched. Waiting for Ruby harness to write result JSON.", bootstrap_path
    except (OSError, ValueError, TypeError) as exc:
        cleanup_bootstrap_plugin(bootstrap_path)
        return False, f"Launch failed: {exc}", None


def wait_for_result(result_path: str, timeout_seconds: int) -> Optional[dict]:
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        if os.path.isfile(result_path):
            try:
                with open(result_path, "r", encoding="utf-8") as f:
                    return json.load(f)
            except (OSError, ValueError, TypeError, json.JSONDecodeError):
                pass
        time.sleep(1.0)
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="SketchUp adapter for PDF Vector Importer QA.")
    parser.add_argument("--config", help="Path to qa_config.json", required=False)
    parser.add_argument("--test-id", required=True, help="Test ID, e.g. SU-OCG-001")
    parser.add_argument("--input", required=True, help="Input PDF path")
    parser.add_argument("--preset", default="Full", help="Import preset name")
    parser.add_argument("--page-range", default="1", help="Page range string")
    parser.add_argument("--output-dir", help="Optional output directory")
    parser.add_argument("--notes", help="Optional notes")
    parser.add_argument("--layers-min-populated", type=int, default=0)
    parser.add_argument("--runtime-cap-seconds", type=int, default=0)
    parser.add_argument("--timeout-seconds", type=int, default=180)
    parser.add_argument("--dry-run", action="store_true", help="Do not launch SketchUp; emit a starter result only.")
    args = parser.parse_args()

    cfg = load_json(args.config)
    config_dir = str(Path(args.config).expanduser().resolve().parent) if args.config else os.getcwd()
    sketchup_cfg = cfg.get("sketchup", {})

    with tempfile.TemporaryDirectory(prefix="bc_pdf_su_qa_") as td:
        payload_path = os.path.join(td, f"{args.test_id}_payload.json")
        result_path = os.path.join(td, f"{args.test_id}_result.json")

        payload = build_payload(args, cfg, result_path, config_dir)
        with open(payload_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)

        if args.dry_run:
            result = {
                "test_id": args.test_id,
                "platform": "SU",
                "status": "DRY_RUN",
                "message": "SketchUp adapter payload created successfully.",
                "payload_json": payload_path,
                "result_json_expected": result_path,
            }
            print(json.dumps(result, indent=2))
            return 0

        if sketchup_cfg.get("automation_supported") is False:
            print(json.dumps({
                "test_id": args.test_id,
                "platform": "SU",
                "status": "BLOCKED",
                "message": "SketchUp automation disabled in config (automation_supported=false).",
                "payload_json": payload_path,
            }, indent=2))
            return 0

        bootstrap_path = None
        try:
            launched, message, bootstrap_path = try_launch_sketchup(
                sketchup_cfg.get("exe"),
                sketchup_cfg.get("ruby_harness"),
                payload_path,
                config_dir,
                sketchup_cfg.get("plugins_dir"),
            )
            if not launched:
                print(json.dumps({
                    "test_id": args.test_id,
                    "platform": "SU",
                    "status": "ERROR",
                    "message": message,
                    "payload_json": payload_path,
                }, indent=2))
                return 2

            result = wait_for_result(result_path, args.timeout_seconds)
            if result is None:
                print(json.dumps({
                    "test_id": args.test_id,
                    "platform": "SU",
                    "status": "TIMEOUT",
                    "message": message,
                    "payload_json": payload_path,
                    "result_json_expected": result_path,
                }, indent=2))
                return 3

            print(json.dumps(result, indent=2))
            return 0
        finally:
            cleanup_bootstrap_plugin(bootstrap_path)


if __name__ == "__main__":
    raise SystemExit(main())
